# Generated by Django 4.1.5 on 2023-01-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre', max_length=100)),
                ('resumen', models.CharField(help_text='Resumen', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre', max_length=64)),
                ('peliculas', models.ManyToManyField(to='index.peliculas')),
            ],
        ),
    ]
